FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && \
    apt-get install -y build-essential libffi-dev python3-dev gnupg && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt /app/

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

RUN apt-get purge -y build-essential libffi-dev python3-dev gnupg && \
    apt-get autoremove -y

COPY . /app/

CMD ["python", "scheduler.py"]