FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

COPY . .

RUN if [ -f requirements.txt ]; then \
        pip install --upgrade pip && \
        pip install -r requirements.txt; \
    fi

CMD ["python", "runner.py"]